//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniqueRegionNamesPatcher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UniqueRegionNamesPatcher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [HoldMap]
        ///(-19,34) = [&quot;Solitude&quot;]
        ///(-18,34) = [&quot;Solitude&quot;]
        ///(-17,34) = [&quot;Solitude&quot;]
        ///(-16,34) = [&quot;Solitude&quot;]
        ///(-15,34) = [&quot;Solitude&quot;]
        ///(-14,34) = [&quot;Solitude&quot;]
        ///(-13,34) = [&quot;Solitude&quot;]
        ///(-19,33) = [&quot;Solitude&quot;]
        ///(-18,33) = [&quot;Solitude&quot;]
        ///(-17,33) = [&quot;Solitude&quot;]
        ///(-16,33) = [&quot;Solitude&quot;]
        ///(-15,33) = [&quot;Solitude&quot;]
        ///(-14,33) = [&quot;Solitude&quot;]
        ///(-13,33) = [&quot;Solitude&quot;]
        ///(-22,32) = [&quot;Solitude&quot;]
        ///(-21,32) = [&quot;Solitude&quot;]
        ///(-20,32) = [&quot;Solitude&quot;]
        ///(-19,32) = [&quot;Solitude&quot;]
        ///(-18,32) = [&quot;Solitude&quot;]
        ///(-17,32) = [&quot;Solitude&quot;]
        ///( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cellmap {
            get {
                return ResourceManager.GetString("cellmap", resourceCulture);
            }
        }
    }
}
